config/routes.rb
CSPortal::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :topics
  resources :comments
  resources :ratingtopics
  root 'home#index'

  match '/about', to: 'home#about', via: 'get'
  match '/register', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/compose', to: 'topics#new', via: 'get'
  match '/main', to: 'users#show', via: 'get'
  match '/topic', to: 'topics#show', via: 'get'
  match '/generate', to: 'comments#new', via: 'get'

  match '/search', to: 'topics#search', via: 'post'
  match '/like', to: 'topics#like', via: 'post'
   match '/dislike', to: 'topics#dislike', via: 'post'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	#include Elasticsearch::Model
  #include Elasticsearch::Model::Callbacks
 include Tire::Model::Search
  include Tire::Model::Callbacks 
  
	belongs_to :user
	has_many :comments, dependent: :destroy
	#default_scope -> { order('created_at DESC') }
	#after_initialize :init
	validates :user_id, presence: true
	validates :subject, presence: true, length: {maximum: 50}
	validates :body, presence: true, length: {maximum: 1000}
	validates :professor_name, length: {maximum:30}
	validates :course_number, :numericality => { :only_integer => true }, :allow_nil => true

	#index_name BONSAI_INDEX_NAME

    #def init
     # self.rating = 0       #will set the default value only if it's nil
    #end

	# searchable do
	# 	text :subject, :professor_name, :course_number
	# en

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	 before_action :signed_in_user, only: [:create, :destroy, :new, :edit, :update, :like, :dislike]
   before_action :correct_user,   only: [:destroy, :edit, :update]
   
  def show
      @user = current_user if signed_in?
      @topic = Topic.find(params[:id])
  end

	def new
    @user = current_user
		@topic = current_user.topics.build if signed_in?
	end

	def create
    @user = current_user
		@topic = current_user.topics.build(topic_params)
		if @topic.save
			flash[:success] = "Topic created!"
			redirect_to main_path
		else
			render 'new'
		end	
 	end

  def edit
    @user = current_user if signed_in?
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      flash[:success] = "Topic updated"
      redirect_to topic_path(@topic)
    else
      render 'edit'
    end
  end

	def destroy
    @topic.destroy
    flash[:success] = "Topic has been deleted!"
    redirect_to root_path
	end

  def search
    @user = current_user if signed_in?
    #@topics = Topic.search(params[:topic]).records
    @topics = Topic.search params[:topic], :page => ( params[:page] || 1 ), :per_page => 10
    # @topics = Topic.search do 
    #   fulltext params[:topic]
    #   paginate(page: params[:page], :per_page =>10)
    # end.results          
  end

  def like
    @user = current_user if signed_in?
    @topic = Topic.find(params[:id])
    #if(Ratingtopic.find(:topic_id => params[:id], :user_id => @user))
    if(Ratingtopic.find_by(:topic_id => params[:id], :user_id => @user.id))
      flash[:error] = "You are already rated this topic"
      redirect_to :back
    else
      @topic.update_column(:rating,@topic.rating+1)
      @ratingtopic = Ratingtopic.new(:topic_id =>params[:id], :user_id =>@user.id)
      @ratingtopic.save
      @topic.update_index
      flash[:success] = "You rated this topic successfully"
      redirect_to :back
      #redirect_to :back
    end
  end

  def dislike
    @user = current_user if signed_in?
    @topic = Topic.find(params[:id])
    #if(Ratingtopic.find(:topic_id => params[:id], :user_id => @user))
    if(Ratingtopic.find_by(:topic_id => params[:id], :user_id => @user.id))
      flash[:error] = "You are already rated this topic"
      redirect_to :back
    else
      @topic.update_column(:rating,@topic.rating-1)
      @ratingtopic = Ratingtopic.new(:topic_id =>params[:id], :user_id =>@user.id)
      @ratingtopic.save
      @topic.update_index
      flash[:success] = "You rated this topic successfully"
      redirect_to :back
      #redirect_to :back
    end
  end

private

  	def topic_params
    		params.require(:topic).permit(:subject,:body,:professor_name, :course_number)
  	end

    def correct_user
      #@topic = current_user.topics.find_by(id: params[:id])
      @topic = Topic.find_by(id: params[:id])
      redirect_to main_path if @topic.nil?
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.erb
 <span><h2><%= link_to topic.subject, topic_path(:id => topic.id)%>
 <button type="button" disabled="disabled" title="Number of likes" class="btn btn-default btn-sm"><%=topic.rating%></button></h2></span> 
 <span class="timestamp">

<%if !topic.course_number.nil? && !topic.professor_name.empty?%>
	 CPSC <%=topic.course_number%> | Professor <%=topic.professor_name%>.
 <%elsif !topic.course_number.nil?%>
 	CPSC <%=topic.course_number%> |
 <%elsif !topic.professor_name.empty?%>
 	Professor <%=topic.professor_name%>.
 	<%else%>
<%end%>

Posted by <%= topic.user.name%> -  <%= time_ago_in_words(topic.created_at) %> ago.

  <%if signed_in? %>
	  <% if current_user?(topic.user)%>
	  <%= link_to "edit ", edit_topic_path(topic)%>
	  <%end%>
	 <% if current_user?(topic.user) || current_user.access_level == 1%>
	  <%= link_to "| delete ", topic, method: :delete, data: { confirm: "Are you sure?"}, title: topic.subject %>	 
	 <%end%>
 <%end%>

 <%= link_to "| like ", like_path(:id =>topic.id), :method => :post%>
  <%= link_to "| dislike ", dislike_path(:id =>topic.id), :method => :post%>
  </span>

app/views/topics/edit.html.erb
<% provide(:title, 'Edit topic') %>

<%#= render 'shared/side'%>
<!-- <div class="mainregion"> -->

<div class="row">
  <div class="span6">
  <h1>Edit your topic</h1>
    <%= form_for(@topic) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :subject %>
      <%= f.text_field :subject, :placeholder => "Topic subject" %>

      <%= f.label "Course number" %>
      <%= f.text_field :course_number, :placeholder => "Course number" %>

      <%= f.label "Professor name"  %>
      <%= f.text_field :professor_name, :placeholder => "Professor name" %>

      <%= f.label "Body"  %>
      <%= f.text_area :body, :placeholder => "Post your comment here"  %>

      <%= f.submit "Post", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<!-- </div> -->

app/views/topics/new.html.erb
<% provide(:title, 'Add a topic') %>

<%#= render 'shared/side'%>
<!-- <div class="mainregion"> -->

<div class="row">
  <div class="span6">
  <h1>Add a topic</h1>
    <%= form_for(@topic) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :subject %>
      <%= f.text_field :subject, :placeholder => "Topic subject" %>

      <%= f.label "Course number" %>
      <%= f.text_field :course_number, :placeholder => "Course number only (Optional)" %>

      <%= f.label "Professor name"  %>
      <%= f.text_field :professor_name, :placeholder => "Optional" %>

      <%= f.label "Body"  %>
      <%= f.text_area :body, :placeholder => "Post your comment here"  %>

      <%= f.submit "Post", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<!-- </div> -->

app/views/topics/search.html.erb
<% provide(:title, "Search") %>


<% if @topics.any? %>
	<h1>  (<%= @topics.count %>) topics found</h1>
	<ol class ="topic">
	<% @topics.each do |topic| %>
 	 <!-- do smth with title -->
	<li>
		 <span><h2><%= link_to topic.subject, topic_path(:id => topic.id)%>
		 <button type="button" disabled="disabled" title="Number of likes" class="btn btn-default"><%=topic.rating%></button></h2></span>

		 
		 <span class="timestamp">
		 	CPSC <%=topic.course_number%> | Professor <%=topic.professor_name%>.
		     Posted by <%= topic.id%> -  <%= time_ago_in_words(topic.created_at) %> ago.

		  <% if current_user?(topic.user) %>
		  <%= link_to "edit ", edit_topic_path(topic)%>
		  <%= link_to "| delete ", topic, method: :delete, data: { confirm: "Are you sure?"}, title: topic.subject %>
		 
		 <%end%>
		  <%#= link_to "| Upvote ", rate_path(:id =>topic.id), :method => :post%>
		  </span>
 </li>
	<%#=render @topics %>
	<% end %>
	</ol>
	
	<%= will_paginate @topics %>
	<%else%>
	<h1> Sorry, no results were found. </h1>
	<% end %>
<br>
<p><%= link_to "Back to main page", root_path %></p>	

app/views/topics/show.html.erb
<% provide(:title, @topic.user.name) %>

	<h1> <%= @topic.subject %>  <button type="button" title ="Number of likes" disabled="disabled" class="btn btn-default"><%=@topic.rating%></button> </h1>
	<%if !@topic.course_number.nil? && !@topic.professor_name.empty?%>
		 <h4>CPSC <%=@topic.course_number%> | Professor <%=@topic.professor_name%></h4>
	 <%elsif !@topic.course_number.nil?%>
	 	<h4>CPSC <%=@topic.course_number%></h4> 
	 <%elsif !@topic.professor_name.empty?%>
	 	<h4>Professor <%=@topic.professor_name%></h4>
	 	<%else%>
	<%end%>
	 <span class="timestamp">

	  <%if signed_in? %>
		  <% if current_user?(@topic.user)%>
		  	<%= link_to "edit ", edit_topic_path(@topic)%>
		 <%end%>

		  <% if current_user?(@topic.user) || current_user.access_level == 1 %>
		  	<%= link_to "| delete |", @topic, method: :delete, data: { confirm: "Are you sure?"}, title: @topic.subject %>
		 <%end%>
	 <%end%>

	 <%= link_to " like |", like_path(:id =>@topic.id), :method => :post%>
	 <%= link_to " dislike", dislike_path(:id =>@topic.id), :method => :post%>

  </span>
  <br>
	<br>
	<div class="comment">
	<div class="float-left">
	<%= gravatar_for @topic.user%>
	 </div>
	 <div class= "gravatar"> 
	 <h2><%= @topic.user.name %></h2>
	 <span class="timestamp"> <%=@topic.user.education_level%></span>
	</div>
	<div class="clear-all"></div>

	<p><%= @topic.body %> </p>
	<span class="timestamp"><p>
    		Posted by <%= @topic.user.name%> -  <%= time_ago_in_words(@topic.created_at) %> ago.
  			</p></span>
	</div>

	<%if @topic.comments.any?%>
		<%@topic.comments.each do |comment| %>
			<div class="comment">
			<div class="float-left">
			<%= gravatar_for comment.user%>
			 </div>
			  <div class= "gravatar"> 
	 		<h2><%= comment.user.name %></h2>
	 		<span class="timestamp"> <%=comment.user.education_level%></span>
	 		</div>
			<div class="clear-all"></div>
			<p><%= comment.body %> </p>
			<span class="timestamp">
    		<p>Posted by <%= comment.user.name%> -  <%= time_ago_in_words(comment.created_at) %> ago.

    		<%if signed_in? %>
	  			<% if current_user?(comment.user)%>
	  				<%= link_to "edit ", edit_comment_path(comment)%>
	  			<%end%>

	  			<% if current_user?(comment.user) || current_user.access_level == 1 %>
	  				<%= link_to "| delete", comment, method: :delete, data: { confirm: "Are you sure?"}, title: @topic.subject %>
	  			<%end%>
  			<%end%>

  			</p></span>
			</div>
		<%end%>

	<%end%>
	 <h2><%= link_to "Add a comment", generate_path(:id => @topic.id), :class =>"pull-right" %></h2>
	 <br>
	 <p><%= link_to "Back to main page", root_path %></p>