config/routes.rb
CSPortal::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :topics
  resources :comments
  resources :ratingtopics
  root 'home#index'

  match '/about', to: 'home#about', via: 'get'
  match '/register', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/compose', to: 'topics#new', via: 'get'
  match '/main', to: 'users#show', via: 'get'
  match '/topic', to: 'topics#show', via: 'get'
  match '/generate', to: 'comments#new', via: 'get'

  match '/search', to: 'topics#search', via: 'post'
  match '/like', to: 'topics#like', via: 'post'
   match '/dislike', to: 'topics#dislike', via: 'post'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_side.html.erb
<div class="sideregion">
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h2>
      <span class="timestamp"> <%=@user.education_level%></span>

      <br><br>
      <ul class="nav nav-sidebar clear-all">
      		<li><%= link_to "Main", root_path %></li>
      		<li><%= link_to "Update your profile", edit_user_path(current_user)%></li>
          <li><%= link_to "Your topics", main_path%></li>

     		 <li><%= link_to "Add a topic", compose_path %></li>
      		
          </ul>
</div>