config/routes.rb
CSPortal::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :topics
  resources :comments
  resources :ratingtopics
  root 'home#index'

  match '/about', to: 'home#about', via: 'get'
  match '/register', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/compose', to: 'topics#new', via: 'get'
  match '/main', to: 'users#show', via: 'get'
  match '/topic', to: 'topics#show', via: 'get'
  match '/generate', to: 'comments#new', via: 'get'

  match '/search', to: 'topics#search', via: 'post'
  match '/like', to: 'topics#like', via: 'post'
   match '/dislike', to: 'topics#dislike', via: 'post'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "CSPortal", root_path, id: "logo" %>
          <nav>
          <div class ="middle nav">
          <%= form_tag("/search", method: "post", class: "navbar-form") do %>
              <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search for topic" name="topic">
              </div>
            <%end%> 
             
          </div>
            <ul class="nav pull-right">
            <li><%= link_to "Home",root_path %></li>
               <% if signed_in? %>

                <li id="fat-menu" class = "dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%=current_user.name%> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                <li><%= link_to "Your topics", current_user %></li>
                <li><%= link_to "Add a topic", compose_path %></li>
                <li><%= link_to "Update profile", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
                </ul>
              </li>
              <% else %>
              <li><%= link_to "Register", register_path %></li>
               <li><%= link_to "Log in", login_path %></li>
             <% end %> 
            </ul>
          </nav>
        </div>
      </div>
    </header>

    
    <div class="container">
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>